### ISSUE TITLE
Enhancement: take a look at Blend2D and AsmJIT

### ISSUE THREAD

**Issue by dumblob** [daokoder/DaoGraphics#1]
The following popped in my mind when I saw the comment `rendering cubic bezier curves` in the source code. There are running projects for low-level graphical pipeline optimization and high-performance vector graphics computation on CPU.

http://kobalicek.com/cpp.html
https://github.com/kobalicek/asmjit
https://github.com/blend2d

Both are written in C++ and the developer is really eager to work on them already few years. The performance and quality results are quite stunning. It might be worth taking a look at or even start using it. Btw once these projects get reasonably stable, he'll finally continue his work on SVG rendering library and a multiplatform GUI library (see http://kobalicek.com/ for more information).

**Comment by daokoder** [comment]
Thanks for the suggestions, but,

> There are running projects for low-level graphical pipeline optimization and high-performance vector graphics computation on CPU.

DaoGraphics would never support graphics rendering on CPU, because it is too costly. 

> Both are written in C++

DaoGraphics will stay in C, and use no components in C++.

> It might be worth taking a look at or even start using it. ...
> he'll finally continue his work on SVG rendering library 

I am afraid it is not wise to wait for using something that has no certainty regarding its outcome and quality, while we already have something working nicely.

Please keep in mind that, DaoGraphics is intended to be small with minimal dependency.

**Comment by dumblob** [comment]
> DaoGraphics would never support graphics rendering on CPU, because it is too costly.

Yes - I wasn't sure if you plan to support a _2D_ version without the dependency on opengl/graphic_card at some point. Now it's clear, that it'll always be opengl, so there's no doubt we won't need CPU.

> I am afraid it is not wise to wait for using something that has no certainty regarding its outcome and quality, while we already have something working nicely.

Sure - I was just amazed by the efficiency of the algorithms he's using and their high-quality outcomes. His work is not yet published in papers, so there is only one way to grasp the ideas - read the code. And that's exactly what I meant ;)

Anyway, I'm closing this issue as inappropriate according to the DaoGraphics goals.

**Comment by daokoder** [comment]
> Sure - I was just amazed by the efficiency of the algorithms he's using and their high-quality outcomes. His work is not yet published in papers, so there is only one way to grasp the ideas - read the code.

The outcome does look impressive, it may be interesting to read his paper once it is published.
